Story6/urls.py
from django.urls import path

from .views import *

app_name ='Story6'
urlpatterns = [
    path('', index, name ='home'),
    path('profile',profile, name ='profile')
]

story10/urls.py
from django.urls import path

from .views import *

app_name ='story10'
urlpatterns = [
    path('', index, name ='home'),
    path('check_email', check_email, name = 'check_email'),
    path('subscribe', subscribe, name = 'subscribe')
]

story8/urls.py
from django.urls import path

from .views import *

app_name ='story8'
urlpatterns = [
    path('', index, name ='home'),
]

story9/urls.py
from django.urls import path

from .views import *

app_name ='story9'
urlpatterns = [
    path('data/', data_json, name='data'),
    path('', index, name ='home'),
]

storyppw/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from story9.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Story6.urls')),
    path('story-8/', include('story8.urls')),
    path('story-9/', include('story9.urls')),
    path('story-10/', include('story10.urls')),
    path('login/', login, name = 'login'),
    path('story-9/logout/', logout, name = 'logout'),
    path('auth/', include('social_django.urls', namespace='social')),

]

Story6/models.py
from django.db import models
from django.utils.timezone import now
# Create your models here.

class Status(models.Model):
    status = models.CharField(max_length = 300)
    date = models.DateTimeField(default = now)

story10/models.py
from django.db import models

# Create your models here.
class Data(models.Model):
    name = models.CharField(max_length = 300)
    email = models.CharField(max_length = 30)
    password = models.CharField(max_length = 30)

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

Story6/forms.py
from django import forms
from .models import Status

class Status_Form(forms.Form):
    attrs = {
        'class' : 'form-control'
        }
    status = forms.CharField(label = '', required = True, max_length= 300,
                           empty_value= 'Anonymous',widget= forms.Textarea(attrs=attrs))

Story6/views.py
from django.shortcuts import render
from .models import *
from . import forms
from .forms import *
from django.http import HttpResponseRedirect

# Create your views here.

def index(request):
    response = {}
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        status = Status(status = response['status'])
        status.save()
        return HttpResponseRedirect('/')
    status_list = Status.objects.all()
    response = {'form': form, 'status_list': status_list}
    return render(request, 'home2.html' , response)

def profile(request):
    response = {}
    return render(request, 'profile.html', response)

story10/views.py
from django.shortcuts import render
from django.core.validators import validate_email
# from django.core.exception import ValidationError
from django.http import JsonResponse

# Create your views here.
def index(request):
    return render(request, 'myforms.html')

def check_email(request):
    response = {"success":False}
    try:
        print(request.POST['email'])
        validate_email(request.POST['email'])
        response["success"] = True
        print('lewat')
    except:
        response['email'] = "Email anda tidak sesuai"

    return JsonResponse(response)

def subscribe(request):
    if request.method == 'POST':
        response['name'] = request.POST['name']
        response['email'] = request.POST['email']
        response['password'] = request.POST['password']
        Data.objects.create(name=response['name'], email=response['email'],
                              password =response['password'])
    return JsonResponse({'message':'success'})

story8/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    response = {}
    return render(request, 'indexprofile.html', response)

story9/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.http import HttpResponseRedirect
import requests
import json

# Create your views here.

def index(request):
	return render(request, 'books.html')

def data_json(request, search= 'quilting'):
	try :
		search=request.GET["search"]
	except:
		search="quilting"
	getBooksJson = requests.get('https://www.googleapis.com/books/v1/volumes?q='+search)
	jsonParsed = getBooksJson.json()
	return JsonResponse(jsonParsed)

def login(request):
	response = {}
	if request.user.is_authenticated:
		request.session['user'] = request.user.username
		request.session['email'] = request.user.email

		request.session.get('counter', 0)
		print(dict(request.session))
		for key, value in request.session.items():
			print('{} => {}'.format(key, value))
	return render(request, 'login.html', response)


def logout(request):
	request.session.flush()
	return HttpResponseRedirect('/story-9')

def add_Fav(request):
	print(dict(request.session))
	request.session['counter'] = request.session['counter'] + 1
	return HttpResponse(request.session['counter'], content_type = "application/json")

def remove_Fav(request):
	request.session['counter'] = request.session['counter'] - 1
	return HttpResponse(request.session['counter'], content_type = "application/json")

Story6/templates/create_sced.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>

  <body>
    <div class="grid-x" style="margin: 20px">
    <div class="cell small-1">

    </div>
    <div  style="background: #eaeaea; padding: 25px; border-radius: 30px" class="cell small-10">
        <section name="form">
            <h2 style="color: #2c3e50">Create Schedule</h2>
            <form action="{% url 'profilenadia:schedule_pos' %}" id="form", method="POST">
                {% csrf_token %}
                {{ Agenda_Form }}
                <br>
                <button type="submit" class="button">Submit</button>
            </form>
        </section>
    </div>
    <div class="cell small-1"></div>

</div>


  </body>
</html>

Story6/templates/home.html
<html>
<head>
  <center><h1>Hello, apa kabar?</h1></center>
</head>

<body>

  <div class="grid-x" style="margin: 20px">
    <div class="cell small-1">

    </div>
    <div  style="background: #eaeaea; padding: 25px; border-radius: 30px" class="cell small-10">
        <section name="form">
            <h2 style="color: #2c3e50">What is happening?</h2>
            <form action="{% url 'Story6:home' %}" id="form", method="POST">
                {% csrf_token %}
                {{ form }}
                <br>
                <button type="submit" class="button">Submit</button>
            </form>
        </section>
    </div>
    <div class="cell small-1"></div>

  <section class="result">
    {% for result in status_list %}
<div>
    <p>
      {{ result.status }}
    </p>
    <p>
          {{ result.date }}
        </p>
  </div>
  {% endfor %}
  </section>

</body>
</html>

Story6/templates/home2.html
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Nadia Syafitri</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="nadia.syafitri@ui.ac.id">
		<meta name="robots" content="index, follow">

		<link rel="stylesheet" href="{%static "css/styles.css" %}">

		<!-- Bootstrap Core CSS file -->
		<link rel="stylesheet" href= "{%static "css/bootstrap.min.css" %}">
	</head>
	<body style="background: #f0f0ed">
		<div class="row">
			<div class="col-md-6">
				<div class="form-css">
			<center><h2 id="Headerfont" style="color: #fffcf4"> Hello, apa kabar?</h2></center>
			<section name="form">
					<form action="{% url 'Story6:home' %}", method="POST">
							{% csrf_token %}
							{{ form }}
							<br>
							<br>
							<center><button type="submit" class="button" id="submit">Submit</button></center>
					</form>
			</section>
		</div>
		</div>
		<div class="col-md-6" id="hasil">
		<section class="result" style="font-family: montserrat; color: black">
			{% for result in status_list %}
		<div class="dingdong">
			<p>
				{{ result.status }}
			</p>
			<p>
						{{ result.date }}
					</p>
		</div>
		{% endfor %}
	</section>
</div>
</div>

</body>
</html>

Story6/templates/navbar.html
{% block content %}
<nav class="navbar navbar-fixed-top" style="background-color: #F9FAD1" role="navigation">
<div class="container-fluid">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'Story6:home' %}">Nadia Syafitri</a>
  </div>
  <!-- /.navbar-header -->

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
  </div>
  <!-- /.navbar-collapse -->
</div>
<!-- /.container-fluid -->
</nav>
{% endblock %}

Story6/templates/page2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Portofolio</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%static "css/thumbnail-gallery.css"%}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    {% block content %}{% include 'navbar.html' %}{% endblock %}


    <!-- Page Content -->
    <div class="container">

      <h1 class="my-4 text-center text-lg-left">Portofolio</h1>

      <div class="row text-center text-lg-left">

        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1935071/screenshots/4575482/sdfsffd.png" alt="" >
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://i.pinimg.com/564x/b1/2e/17/b12e17bb7ea033364c121a5e8a2594a7.jpg" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1094383/screenshots/4674641/hq2.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1588664/screenshots/4539133/0000.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1588664/screenshots/4677338/end.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/2933/screenshots/4660545/ezgif.com-video-to-gif-long.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/793057/screenshots/3031884/pull-to-refresh_1.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/1167581/screenshots/3135876/render.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/93245/screenshots/2947795/job_app_concept.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/572419/screenshots/4477691/set7.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/507649/screenshots/3439906/afterpay_app_onboarding.gif" alt="">
          </a>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-6">
          <a href="#" class="d-block mb-4 h-100">
            <img class="img-fluid img-thumbnail" src="https://cdn.dribbble.com/users/62549/screenshots/4578758/booksley.gif" alt="">
          </a>
        </div>
      </div>

    </div>
    <!-- /.container -->


    <!-- Bootstrap core JavaScript -->
    <script src="{%static "js/jquery.min.js"%}"></script>
    <script src="{%static "js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>

Story6/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Nadia Syafitri</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="nadia.syafitri@ui.ac.id">
		<meta name="robots" content="index, follow">

		<!-- icons -->
		<link rel="icon" href="https://banner2.kisspng.com/20180330/whq/kisspng-common-daisy-flower-white-stock-photography-daisy-5abee3d5168134.7019189615224596050922.jpg" type="image/gif" sizes="16x16">

		<!-- Bootstrap Core CSS file -->
		<link rel="stylesheet" href= "{%static "css/bootstrap.min.css" %}">

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" href="{%static "css/styles.css" %}">

		<!-- Conditional comment containing JS files for IE6 - 8 -->
		<!--[if lt IE 9]>
			<script src="assets/js/html5.js"></script>
			<script src="assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>


		{% block content %}{% include 'navbar.html' %}{% endblock %}

			<!-- /.row -->

			<div class="row margin-b-2">
				<div class="col-sm-6">
					<div class="whitebox" id="border1">
						<img id="display" src="{%static "img/Nadia.jpg" %}"; width="150"; height="150">
						<h1 id="Headerfont1"> Nadia Syafitri </h1>
						<h4 id="itemfont2"> Jakarta, January 17th 2000<h4>
							<p id="itemfont3"> I'm currently pursuing Computer Science Degree <br>
								at University of Indonesia</p>

					</div>
				</div>
				<div class="col-sm-6">
					<div class="educationbox">
						<div class="row" id="row-1">
							<p id= timeline1>SMPN 85 Jakarta <br> &nbsp &nbsp &nbsp 2011-2014</p>
						</div>
						<div class="row">
							<p id= timeline2>SMAN 34 Jakarta <br> &nbsp &nbsp &nbsp 2014-2017</p>
						</div>
					</div>
					<h1 id="Headerfont2"> EDUCATION </h1>
				<br>
				</div>
			</div>
			<!-- /.row -->

			<div class="row margin-b-2">
				<div class="col-sm-6" >
					<div class="row-md-2" style="padding-bottom:20px;">
					<div class="bluebox">
						<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/5dbf16c6dbb044f4b346c47d81a5a89f?quality=95&fake=.png"; width="80"; height="80">
						<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/b8427b2b677f445398dd0fe7997a9eb6?quality=95&fake=.png"; width="80"; height="80">
						<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/beaa9dc0e4c24fb69ea74082ee0ebd31?quality=95&fake=.png"; width="80"; height="80">
						<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/7f301779ee8f4fb6a658ac5330c3bfd6?quality=95&fake=.png"; width="80"; height="80">
					</div>
						<div class="educationbox" id="orangesize">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/d684d74b26054e07ab4fbe63c4407f06?quality=95&fake=.png"; width="80"; height="80">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/0053c5ff84624f6e821744e5b147e4e9?quality=95&fake=.png"; width="80"; height="80">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/780c1e37d53c4da6a49e9bb0e7ae99e4?quality=95&fake=.png"; width="80"; height="80">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/9ca0b19918a84353829b8cebdef85c57?quality=95&fake=.png"; width="80"; height="80">
							<img id="display3" src="https://marvel-live.freetls.fastly.net/canvas/2018/9/4325f6b78681421597583a5b7ce8fc1c?quality=95&fake=.png"; width="80"; height="80">
						</div>
					</div>
				</div>

				<div class="col-sm-6">
					<div class="element">
					<h3 class="UIUXmargin" id="Headerfont"> UI/UX Designer </h3>
					<div class="caption UIUXmargin">
						<ol id="itemfont">
							<li> Gathering and evaluating user requirements, in collaboration with product managers and engineers </li>
							<li> Illustrating design ideas using storyboards, process flows and sitemaps </li>
							<li>Designing graphic user interface elements, like menus, tabs and widgets</li>
						</ol>
					</div>
				</div class="row">
				<h1 id="Headerfont2"> WORK EXPERIENCE </h1>
				</div>
			</div>
			<!-- /.row -->

			<div class="row margin-b-2">
				<div class="col-sm-6">
					<div class="educationbox">
						<h3 class="UIUXmargin" id="Headerfont">COMPFEST X</h3>
							<h5 class="UIUXmargin" id="italic"> Staff of Playground</h5>
						<ul id="itemfont4">
							<li>Person in Charge Playground on Main Event</li>
							<li>Person in Charge Open Registration Playground</li>
							<li>Approached more than 20 IT startups for the exhibiton.</li>
					</div>
					<h1 id="Headerfont2"> VOLUNTEERS </h1>
				</div>
				<div class="col-sm-6">
					<div class="whitebox" id="border2">
						<img id="display2" src="https://i.pinimg.com/564x/2e/4b/c5/2e4bc5ab1f9cdbc10d54bdac33d26ccb.jpg"; width="150"; height="150">
					</div>
					<h1 id="Headerfont2"><a href="{% url 'Story6:home'%}"> PORTOFOLIO</a> </h1>
				</div>
			</div>
			<!-- /.row -->


		<!-- JQuery scripts -->
	    <script src="{%static "js/jquery-1.11.2.min.js"%}"></script>

		<!-- Bootstrap Core scripts -->
		<script src="{%static "js/bootstrap.min.js"%}"></script>
  </body>
</html>

Story6/templates/schedule.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Nadia Syafitri</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="nadia.syafitri@ui.ac.id">
		<meta name="robots" content="index, follow">

		<!-- icons -->
		<link rel="icon" href="https://banner2.kisspng.com/20180330/whq/kisspng-common-daisy-flower-white-stock-photography-daisy-5abee3d5168134.7019189615224596050922.jpg" type="image/gif" sizes="16x16">

		<!-- Bootstrap Core CSS file -->
		<link rel="stylesheet" href= "{%static "css/bootstrap.min.css" %}">

		<!-- Override CSS file - add your own CSS rules -->
		<link rel="stylesheet" href="{%static "css/styles.css" %}">

		<!-- Conditional comment containing JS files for IE6 - 8 -->
		<!--[if lt IE 9]>
			<script src="assets/js/html5.js"></script>
			<script src="assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
    {% block content %}{% include 'navbar.html' %}{% endblock %}
    <div class="container">
    <div class="col-1">
      <div class="row-md-10">
    <section name="form">
          <h2>Write your Schedule!</h2>
          <form id="form" method="POST" action="{% url 'profilenadia:schedule' %}">
              {% csrf_token %}
              {{ Agenda_Form }}
              <br>
              <button type="submit" class="save btn btn-default">Add</button>
							<a href="{% url 'profilenadia:delete_all' %}"  class="save btn btn-default">Delete All</a>
          </form>
      </section>
    </div>
  </div>

<div class="container">
  <div class="col-md-7">
  <div class="row-md-10">
      <table class="table">
        <thead>
            <th>Name of activity</th>
            <th>Place</th>
            <th>Date</th>
            <th>Time</th>
            <th>Category</th>
        </thead>
            <tbody>
                {% for i in schedule %}
                <tr>
                    <td> {{ i.nama_kegiatan }} </td>
                    <td> {{ i.tempat }} </td>
                    <td> {{ i.date }} </td>
                    <td> {{ i.time }} </td>
										<td> {{ i.kategori }} </td>
									 </tr>
                {% endfor %}
            </tbody>
        </table>
  </div>
</div>

  </body>
  </html>

story10/templates/myforms.html
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Nadia Syafitri</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="Description" lang="en" content="ADD SITE DESCRIPTION">
		<meta name="author" content="nadia.syafitri@ui.ac.id">
		<meta name="robots" content="index, follow">

		<link rel="stylesheet" type="text/css" href="{%static "css/style-profile.css" %}">

		<!-- Bootstrap Core CSS file -->
		<link rel="stylesheet" href= "{%static "css/bootstrap.min.css" %}">


    <!-- JQuery File -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
		<script src="{%static 'js/bootstrap.min.js'%}"></script>
	  <script src="{%static 'js/js-profile.js'%}"></script>
		<script src="{%static 'js/javascriptForm.js'%}"></script>
	</head>

<body onload="myFunction()" style="margin:0;">
	<div id="loader" class="text-center" style="padding-top: 25vh;">
		<img src="https://upload.wikimedia.org/wikipedia/commons/b/b1/Loading_icon.gif" alt="">
	</div>


	<div style="display:none;" id="myDiv" class="container animate-bottom" id="myDiv">
      <div class="row">
      <h1 class="Headerfont">Nadia Syafitri</h1>
      <br>
					<button type="button">Click Me!</button>
					<br>
              <br>
              <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
              <div class="panel panel-custom">
                  <div class="panel-heading" role="tab" id="headingOne">
                      <h4 class="panel-title">
                          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                              <i class="glyphicon glyphicon-plus"></i>
                              Profile
                          </a>
                      </h4>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                      <div class="panel-body animated zoomOut">
                        <img id="display" src="{%static "img/Nadia.jpg" %}"; width="150"; height="150">
                        <h1 id="Headerfont1"> Nadia Syafitri </h1>
                        <h4 id="itemfont2"> Jakarta, January 17th 2000</h4>
                          <p id="itemfont3"> I'm currently pursuing Computer Science Degree <br>
                            at University of Indonesia</p>
                      </div>
                  </div>
              </div>
              <div class="panel panel-custom">
                  <div class="panel-heading" role="tab" id="headingTwo">
                      <h4 class="panel-title">
                          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                              <i class="glyphicon glyphicon-plus"></i>
                              Experience and Achievements
                          </a>
                      </h4>
                  </div>
                  <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                      <div class="panel-body animated zoomOut" id="maintheme">
                        <h3 id="Headerfont">COMPFEST X</h3>
                          <h5 id="italic"> Staff of Playground</h5>
                        <ul id="itemfont4">
                          <li>Person in Charge Playground on Main Event</li>
                          <li>Person in Charge Open Registration Playground</li>
                          <li>Approached more than 20 IT startups for the exhibiton.</li>
                        </ul>
                        <h3 id="Headerfont">BEM Fasilkom UI</h3>
                            <h5 id="italic"> Staff of Public Relation</h5>
                          <ul id="itemfont4">
                            <li>Person in Charge for all BEM Fasilkom's Social Media</li>
                            <li>Have made more than 20 publication contents since February 2018 until now.</li>
                            <li>Several times being MCs</li>
                          </ul>
                          <h3 id="Headerfont">Open House Fasilkom UI</h3>
                              <h5 id="italic"> Staff of Creative</h5>
                            <ul id="itemfont4">
                              <li>Person in Charge for Decoration</li>
                              <li>Made ID Card Design </li>
                            </ul>
                      </div>
                      </div>
                  </div>
              </div>
              <div class="panel panel-custom">
                  <div class="panel-heading" role="tab" id="headingThree">
                      <h4 class="panel-title">
                      <i class="glyphicon glyphicon-plus"></i>
                          <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                              Activity List
                          </a>
                      </h4>
                  </div>
                  <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                      <div class="panel-body animated zoomOut">
                          Saya hanya sedang sibuk berkuliah di Fasilkom UI dan sibuk mengerjakan tugas-tugas akademis serta non-akademis
													yang saya ikuti.
                  </div>
              </div>
          </div>
      </div>
      <form>
			{% csrf_token %}
          Name:<br>
      <input type="text" id=""="id_nama" name="name" value="">
        <br>
          Email:<br>
      <input type="email" id="id_email" name="email" placeholder="nadia@example.com">
			<div id="email_notice"></div>
				<br>
        Password:<br>
    <input type="password" id="id_password" name="password" value="">
      <br><br>
      <input id="id_button" type="submit" value="Submit" disabled>
  </form>
  </div>


</body>

</html>